"""initial

Revision ID: 3c82fbdcce8f
Revises: 
Create Date: 2025-11-07 17:09:13.405913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c82fbdcce8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=256), nullable=True),
    sa.Column('institute', sa.String(length=256), nullable=True),
    sa.Column('cgpa', sa.String(length=64), nullable=True),
    sa.Column('passing_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=512), nullable=True))
        batch_op.alter_column('organization',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('year',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=512),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('year',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('organization',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('title')

    op.drop_table('skill')
    op.drop_table('education')
    op.drop_table('achievement')
    # ### end Alembic commands ###
