"""Add image_file to Certification model

Revision ID: 64ed07a75625
Revises: 3c82fbdcce8f
Create Date: 2025-11-07 23:57:52.078079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ed07a75625'
down_revision = '3c82fbdcce8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certification', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
